.PHONY: lint lint-c

LINT_C_SRCS := $(filter-out $(THIRD_PARTY_SRC),$(sort \
	$(SRCS) \
	$(TEST_PROTOCOL_SRCS) \
	$(TEST_SERVER_PEERS_SRCS) \
	$(TEST_SERVER_DATA_SRCS) \
	$(TEST_SERVER_HANDLERS_SRCS) \
	$(TEST_CLIENT_PEERS_SRCS) \
	$(TEST_CLIENT_HANDLERS_SRCS) \
	$(SITEST_SRC) \
	$(TEST_SUPPORT_SRCS) \
	$(TOOL_SRCS) \
	$(PEERFORGE_SERVER_SRCS)))

lint:
	tools/lint.sh $(CFLAGS) $(TEST_INCLUDES) -- $(LINT_C_SRCS)

lint-c: lint
